name: Build deb

on:
  workflow_dispatch:

jobs:
  kbuild-docker:
    runs-on: "ubuntu-latest"
    container:
        image: echerkasov/kbuild:test2
    steps:
      - uses: actions/checkout@master
      - name: Build deb package for amd64
        run: dpkg-buildpackage -rfakeroot -us -uc -tc -b
