name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: sudo apt-get install -y build-essential libatasmart-dev libjansson-dev
      - name: Autoconf
        run: autoreconf --install
      - name: Configure
        run: ./configure --prefix=/usr ${CONFIGURE_FLAGS}
      - name: Build
        run: make
      - name: Install
        run: sudo make install
