name: Build deb

on:
  workflow_dispatch:

jobs:
  kbuild-docker:
    runs-on: "ubuntu-latest"
    container:
        image: echerkasov/kbuild:test2
    steps:
      - uses: actions/checkout@master
      - name: Build deb package for amd64
        run: dpkg-buildpackage -rfakeroot -us -uc -tc -b
      - name: Build deb package for arm64
        run: dpkg-buildpackage -rfakeroot -us -uc -tc -b -a arm64 -d
      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R
          ls -R ~/
      - name: Create archive with deb packages
        run: tar czvf debs.tar.gz "../libkeapi3*.deb"
      - uses: actions/download-artifact@v2
        with:
          name: deb packages
          path: debs.tar.gz
