name: Build deb

on:
  workflow_dispatch:

jobs:
  kbuild-docker:
    runs-on: "ubuntu-latest"
    container:
        image: echerkasov/kbuild:test2
    steps:
      - uses: actions/checkout@master
      - name: Prepare directory for artifacts
        run: |
          mkdir -p ~/artifacts/amd64
          mkdir -p ~/artifacts/arm64
      - name: Build deb package for amd64
        run: |
          dpkg-buildpackage -rfakeroot -us -uc -tc -b
          cp ../libkeapi*_amd64* ~/artifacts/amd64
      - name: Build deb package for arm64
        run: |
          dpkg-buildpackage -rfakeroot -us -uc -tc -b -a arm64 -d
          cp ../libkeapi*_arm64* ~/artifacts/arm64
      - uses: actions/upload-artifact@v2
        with:
          name: deb packages
          path: ~/artifacts/
