name: Build deb

on:
  workflow_dispatch:

jobs:
  kbuild-docker:
    runs-on: "ubuntu-latest"
    container:
        image: echerkasov/kbuild:test2
    steps:
      - uses: actions/checkout@master
      - name: Prepare directory for artifacts
        run: |
          mkdir -p $HOME/artifacts/amd64
          mkdir -p $HOME/artifacts/arm64
      - name: Build deb package for amd64
        run: |
          dpkg-buildpackage -rfakeroot -us -uc -tc -b
          cp ../libkeapi3*_amd64* $HOME/artifacts/amd64
      - name: Build deb package for arm64
        run: |
          dpkg-buildpackage -rfakeroot -us -uc -tc -b -a arm64 -d
          cp ../libkeapi3*_arm64* $HOME/artifacts/arm64
      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R ../
          ls -R ~/
      - name: Create archive with deb packages
        run: tar czvf $HOME/debs.tar.gz $HOME/artifacts/
      - uses: actions/download-artifact@v2
        with:
          name: deb packages
          path: $HOME/debs.tar.gz
